# Optional GitLab CI mirror of `.github/workflows/python-app.yml`.
# https://medium.com/swlh/automate-testing-with-gitlab-pipelines-4d35c72c18a
default:
    image: python:3.12
    before_script:
       - python -m pip install --upgrade pip
       - pip install -e ".[test]"
stages:
    - test
test:
    parallel:
        matrix:
            - PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.13"]
    image: python:$PYTHON_VERSION
    script:
        - pytest --cov --cov-report=term --cov-report=xml
    coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
